name: Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    name: Format and lint Python code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.14" ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          # Install a specific version of uv.
          version: "0.11.26"
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --all-extras --locked
      - name: Check code formatting with black
        run: |
          uv run --locked python -m black --check .
      - name: Check typing with mypy
        run: |
          uv run --locked python -m mypy --strict .

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          languages: ${{ matrix.language }}
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          category: "/language:${{matrix.language}}"


  sonarqube:
    name: SonarQube Scan

    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !contains(github.event.pull_request.labels.*.name, 'dependencies/renovate') }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Read version from file
        id: version
        run: |
          echo "VERSION=$(cat _version.txt | tr -d '\r\n')" >> $GITHUB_OUTPUT

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.VERSION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
